version: "3.5"

services:
  db:
    container_name: db
    image: postgres:9.5
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vacinacao
